# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/repo2graph',
                'doc_host': 'https://jwengr.github.io',
                'git_url': 'https://github.com/jwengr/repo2graph',
                'lib_path': 'repo2graph'},
  'syms': {'repo2graph.core': {'repo2graph.core.foo': ('core.html#foo', 'repo2graph/core.py')}}}
