"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_retrieval.ipynb.

# %% auto 0
__all__ = ['BM25_TOKENIZER', 'build_bm25_retriever']

# %% ../nbs/02_retrieval.ipynb 3
import bm25s
from transformers import AutoTokenizer

BM25_TOKENIZER = 'huggingface/CodeBERTa-small-v1'

def build_bm25_retriever(corpus, tokenizer:AutoTokenizer = None):
    if tokenizer is None:
        tokenizer = AutoTokenizer.from_pretrained(BM25_TOKENIZER)
    pass
